### PR TITLE
Detect which Python version is available and run tests using it

### PR DESCRIPTION
**Pull request by pabs3**
Allow overriding the Python version.

### CODE REVIEW

**Comment by mnauw** [comment]
On my system, the auto-detection leads to a regression.  The main python is still `python2` along with installed mercurial.  However, `python3` is available as well, and that one is picked by the auto-detection although no `python3` mercurial is available, as is then found out later on.

In overall, there are other customary ways to select which python to use, e.g. `virtualenv` (or alike).  And those techniques also arrange for proper `PATH`, `PYTHONPATH` (and/or symlink) setup for that particular python (environment) to be selected upon subsequent execution.  With that approach, one can easily run tests in varying environments (python version, mercurial version), as I have been doing so far.

**Comment by pabs3** [comment]
On a native Python 3 system (Debian 11 bullseye), where Mercurial does
not support Python 2 and where Python 2 is not installed, the current
test suite fails because python is not in PATH. For the Debian package
of git-remote-hg, we worked around this by adding a new directory to
PATH containing a python -> /usr/bin/python3 symlink. In the Debian
package build scenario, using virtualenv is not appropriate.

I think the regression might be solvable by adding testing for the
mercurial module for each Python version being tested. Sound OK?

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by mnauw** [comment]
So Debian no longer provides a default `python` command/symlink somewhere in (default) `PATH` (if it ever did, Ubuntu did at least)? That is a very minimal interpretation of https://www.python.org/dev/peps/pep-0394/.  Basically, it no longer provides an environment (API) as provided by a `virtualenv` (which does provide `python`).

That way, we lose the "symlink substitution way" to have `python` invocation automagically select the desired python, and then have to resort to alternative substitution approaches for that to work out, such as (e.g.)  `PYTHON`.  So that then requires lots of `PYTHON` sprinkling and duplicating (as suggested here) in many places.

Also, all simple python scripts will have to start hard-coding `python3` in their shebang (if the shebang is not to be manipulated by some setuptools at some stage, etc).  Perhaps that is not a problem now since `python2` is probably considered dead.  But it is going to be great fun all over again if/when we ever get to `python4`.

Somehow it feels a simpler solution (of far larger scope and utility) would be to properly provide a python symlink.  But since it may be hard to move a mountain (distro), the suggested workaround (with additional mercurial testing) is then an option.

**Comment by pabs3** [comment]
For Debian bullseye these packages and files are provided:

python-is-python2: /usr/bin/python
python-is-python3: /usr/bin/python
python2-minimal: /usr/bin/python2
python3-minimal: /usr/bin/python3

All packages in Debian bullseye are depending on python3 and python2 is
only available for compatibility and python-is-* are not installed by
default so an unversioned python is not available by default but folks
can install one of them to get it installed if necessary for code not
shipped by the distro. The python-is-* packages say "No packages may
declare dependencies on this package" in their description, so the
Debian git-remote-hg package cannot build-depend on them.

Before Debian bullseye, /usr/bin/python only ever pointed to Python 2.

IIRC Arch Linux, old releases had Python 2 at /usr/bin/python and had
Python 3 at /usr/bin/python3 and then later switched /usr/bin/python to
Python 3.

IIRC the way it works with Python setuptools/etc based projects is that
you run setup.py under your desired Python version and it ensures that
version is in the shebang of any installed scripts, I think by
generating a wrapper that imports/runs the installed modules and also
that Python version is used for tests. Since git-remote-hg doesn't have
modules and the main build system is a Makefile, there is no shebang
substitution etc. Right now the Debian git-remote-hg package just has a
patch to change the two shebangs to use python3 and the PATH hack to
make the tests use python3.

Soonish I'll look at extending the Python detection within the tests to
include the mercurial module and probably also editing the shebangs.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by pabs3** [comment]
I've added shebang fixing for the installed scripts and for the scripts
run by the tests. I think that should fix the regression you found and
will eliminate all of the Python related Debian workarounds.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by mnauw** [comment]
Ah ... so that's how Debian intends to go about it ...

That indeed takes care of it.

**Pull request merged**
